### ISSUE TITLE
[Feature] Choosing Color for pen on the top bar

### ISSUE THREAD

**Issue by they10** [pastthepixels/FreePaint#17]
**Is your feature request related to a problem? Please describe.**
Changing color of the pen is hard.

**Describe the solution you'd like**
Instead of the change color of the pen from setting menu, I would like to change it in the top bar without going to the settings.

**Describe alternatives you've considered**
Putting color settings to top bar can be a easier and nicer for most users.

Thank you.

**Comment by pastthepixels** [comment]
Hi! I think I should start off by saying I'm really sorry for not telling anyone I was redesigning FreePaint already; I thought it would be fine to just do it because "nobody would worry about it anyway". However, this is actually one of the things I wanted to address! I think I'll take some time in this comment to show what my plans are (and if you have any suggestions - let me know! FreePaint is FOSS after all.)

First off, here's a mockup I made, badly drawn in FreePaint:
![mockup](https://github.com/pastthepixels/FreePaint/assets/52388215/e9e058dc-b716-44bd-9946-0365cb4f0e3b)

Since making it, I might add a button for layers in the overflow menu rather than on the bar. This is really similar to how Google Drive lets you draw on documents, though:
![screenshot](https://github.com/pastthepixels/FreePaint/assets/52388215/d6eaa02c-4689-426b-adc4-f75c6799423d)

...And here comes the problem. It's Android, so doing something like this is really hard to implement. That doesn't mean it's _impossible_, and since there's interest in it I'll continue to implement this redesign, but it should also be noted that you can't build this with default views and Google once again did some black magic without telling anyone.

Lastly, here's what I managed to implement so far using pre-existing Android views. The main issue with it is you have this button that's pressed to access settings and held to access undoing and redoing, and the overflow menu, which means some common actions are _more_ difficult.
![screenshot](https://github.com/pastthepixels/FreePaint/assets/52388215/055f697a-ecfe-411c-a9ec-62190d1e668d)

Anyway, sorry about the wall of text but I hope that can help to explain what's currently being done to implement this, and make FreePaint in general more accessible!

**Comment by they10** [comment]
oh that's not a problem, the thing you trying to do is great I think. It will look more elegant and easier to use. To be honest I don't understand from coding much, but if it's hard to coding like you wanna do. Maybe you can do bottom and top bar separete. bottom bar can stay like you designed. and you can put top bar to colors, font-size,retake, setting button to top bar. I don't understand from design too much too to be honest, but I like simplicity, and when you said it's hard to coding, I thought something like that. 
![untitled2](https://github.com/pastthepixels/FreePaint/assets/18086948/71ce9925-8a6e-499f-822d-42b08b82334b)


If you wanna continue what you thinking for which is looking great I think, I like it, but you said it's hard to code that, So I thought something like this after read your message for give you a different option and idea. Also if you add save as "jpg and png" options it would be great.

**Comment by pastthepixels** [comment]
Hey! Sorry for the wait. I've gotten to completely redesigning FreePaint; this new layout also removes a lot of lines from the codebase so things should be easier to maintain. Let me know what you think!
Here's a demo video (note that there's top and bottom margins where my status and navigation bars are, but those weren't captured in the recording):

https://github.com/pastthepixels/FreePaint/assets/52388215/661cf9b8-97cf-4684-8463-d1c755fcbcea

**Comment by they10** [comment]
oh no worries, you still here and trying to improve, that's great.

Wow that's looking very cool. Much better than the older version. I think you did a really great job. 
My suggestions about new design and new updates in the future:

1- if we can see last 3 color we chose or if we can create our color palette it would be great. Because on drawing people mostly use 2-3 color together. If you want you can add it to main menu or  above the cancel and ok button on the color picking menu. And also I think maybe you can add stroke size(pen size) to same panel.(color picking panel) Because it's little bit hard to reach to settings to changing pen size.

2- Adding second and different pen style it can be handy to use. (in the future)

-----
But overall I think there is so much progress in the app. You waited long time to update but it was definitely worth it.

**Comment by they10** [comment]
oh I okay, I understand. I think project is going great right now. Especially, I'm happy with optimization. There is no lag and it's very smooth to use it. Thank you for the help. I'll close the topic now as you say.
