### ISSUE TITLE
Wrong File Showing

### ISSUE THREAD

**Issue by T8RIN** [pastthepixels/FreePaint#2]
I just opened svg, and that looks like that ->

![Screenshot_20230903-185721_FreePaint.png](https://github.com/pastthepixels/FreePaint/assets/52178347/0bbe9d80-c59e-4513-b23b-33b3a7358e1a)

My app is opening it as expected ->

![Screenshot_20230903-190534_Image Toolbox (Resizer).png](https://github.com/pastthepixels/FreePaint/assets/52178347/6a1d5d81-0f9b-465e-9eea-5323b832e725)

**Comment by pastthepixels** [comment]
Could you please see if you could upload the SVG you used? I'll have to take a look at it.

I couldn't find any libraries for reading SVGs so I had to write my own importer/exporter. It's pretty barebones at the moment and gets really fussy when you import like 99% of SVGs so that may be the reason why it isn't working.

**Comment by T8RIN** [comment]
> Could you please see if you could upload the SVG you used? I'll have to take a look at it.
> 
> I couldn't find any libraries for reading SVGs so I had to write my own importer/exporter. It's pretty barebones at the moment and gets really fussy when you import like 99% of SVGs so that may be the reason why it isn't working.

I will provide it later

**Comment by T8RIN** [comment]
![hot-dog](https://github.com/pastthepixels/FreePaint/assets/52178347/ad4b0d9c-6225-4a3f-8af7-b87e36f2bf4a)
Here it is

**Comment by pastthepixels** [comment]
While browsers can open this fine, after a bit of looking I think I know what's causing issues here (or at least a couple things to note):
- The image size is `1em`x`1em`. FreePaint can't handle anything other than pixel measurements right now, but what's interesting is neither can Inkscape -- it actually loads the document as really small and doesn't even load the hotdog at all.
- FreePaint breaks at commands like `41.19s-2.96-22.81` or `73c4.22 6.19` because it expects SVG path data that's numbers separated by a space (e.g. `10 20 40 60` or something to denote two points with x and y values). So it likely just skips over those commands and thinks there's an entirely different kind of path happening. This is a crude implementation right now, so in the future I'll work toward ignoring whitespace and adding some path commands used in the SVG.

Also to note, I believe you're using a library in your app to load SVGs as bitmaps which is why it looks fine there (the program can also scale SVGs unlike FreePaint). Unfortunately, I have to manually parse SVGs into FreePaint's classes (it has its own classes for lines, paths, and appearances, for example) so everything can be scalable/editable, which is probably also why it caught the first thing I found (and why I have to manually add each SVG spec).

And thanks for sending the file! That helps quite a bit.

**Comment by T8RIN** [comment]
Okay, i'll wait for updates then :)

**Comment by pastthepixels** [comment]
Sorry for the wait -- I just finished rewriting my SVG path parser to interpret the commands I accept to 100% SVG spec. (Essentially, SVGs are made up with multiple elements, and the path element is a whole can of worms because its attribute `d` contains a bunch of commands and points to draw paths with a bunch of specification.) FreePaint fully supports the `M` and `L` commands now (plus `H` and `V`, and the lowercase versions of these commands) now, so you can finally use whatever kind of whitespace is in the SVG spec and it should work.

Unfortunately FreePaint doesn't support the `c` and `s` commands needed to draw curves, which the hotdog SVG uses extensively. But, if we run it through Inkscape to flatten all the curves... it works! (I also scaled up the image though it works at its original size due to #3 being fixed.)

![hotdog-flat](https://github.com/pastthepixels/FreePaint/assets/52388215/339a4b26-1d6d-4a24-9ebd-d35c8ca57196)


I'll merge the code I have, and I plan to support Bezier curves in the next version of FreePaint so soon this whole SVG should be supported

**Comment by pastthepixels** [comment]
Yeah, no problem!

**Comment by T8RIN** [comment]
:)
