### ISSUE TITLE
[Bug] F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [pastthepixels/FreePaint#24]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/6831284308#L902

as https://github.com/pastthepixels/FreePaint/releases/tag/v1.2.0 is tagged to https://github.com/pastthepixels/FreePaint/commit/f2bf6a02020be4edb4cfbe4b9ad9fa1e4be0ef5b

but APK is built from https://github.com/pastthepixels/FreePaint/commit/4ed875a6f496ac1bedd7e00c012598466172a432

but besides that _(and please in the future always build from the tagged commit or at least remove vcsinfo: https://f-droid.org/docs/Reproducible_Builds/#vcs-info)_ diff log says you've built your APK with Java 21 _(https://f-droid.org/docs/Reproducible_Builds/#mismatched-toolchains)_ right?

diff: [freep5.log](https://github.com/pastthepixels/FreePaint/files/15296799/freep5.log)

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/cf1900e6e961e31f8dd5746c42327476df36c70b

**Comment by pastthepixels** [comment]
Hey! Sorry for causing another build issue for F-Droid...

> and please in the future always build from the tagged commit or at least remove vcsinfo: https://f-droid.org/docs/Reproducible_Builds/#vcs-info

I had no idea AGP 8.3 did that. I've removed vcsinfo just to help with reproducible builds in case I do something silly like this again.
I think the best course of action from here is just to update the APK in the release, and commit removing vcsinfo to the main branch, but if this sounds like a bad idea please let me know!

> diff log says you've built your APK with Java 21 right?

Yes, I did build 1.2.0 with Java 21. I'm planning on using some features from Java 21 (unless it messes up backwards compatibility) so my idea is to move over to building with OpenJDK 21. In hindsight I probably should have said something about that change since F-Droid's YAML for FreePaint builds with OpenJDK 17.
On that note however I'll add build instructions to the Readme to make things easier to reproduce/changes easier to track.

Thanks!

**Comment by licaon-kter** [comment]
you tagged https://github.com/pastthepixels/FreePaint/releases/tag/v1.2.0 to https://github.com/pastthepixels/FreePaint/commit/f2bf6a02020be4edb4cfbe4b9ad9fa1e4be0ef5b

but the APK was built from https://github.com/pastthepixels/FreePaint/commit/4ed875a6f496ac1bedd7e00c012598466172a432

**Comment by pastthepixels** [comment]
Got it. I'll rebuild the apk in the 1.2.0 release with the latest commit from that tag (which will still include vcsinfo but should be built on the latest commit, so when it's compared with the apk F-Droid builds hopefully it'll work!), but then also remove vcsinfo from future builds/tags.

**Comment by licaon-kter** [comment]
Looks like I forgot to post here :)

I've already updated the recipe to pont to 4ed875a so you can keep the apk
