### ISSUE TITLE
[Feature] Draw open paths instead of closed paths with eraser tool

### ISSUE THREAD

**Issue by TechMorgan** [pastthepixels/FreePaint#30]
When using the eraser, instead of creating a closed path to erase the entire segment, I want an option to use a normal eraser to erase specified amount of the line based on where I slide on it.

**Comment by pastthepixels** [comment]
I was actually planning on redesigning the eraser tool to do this by default in 1.3.0 but didn't really revisit FreePaint until now. Basically the plan is to draw a stroke, turn it into a convex shape, and then remove the intersecting area/points from that eraser path. (But again by default because the way I did the eraser tool before was more when this was a proof-of-concept and isn't user friendly.)

**Comment by pastthepixels** [comment]
The eraser tool definitely needed a rewrite. Here's what I did, which also erases from open paths:

https://github.com/user-attachments/assets/b26151d0-5cd4-475f-952d-3f646c7deb81

**Comment by pastthepixels** [comment]
Just merged #34 to v1.3.0 which contains these edits, so I'll close this for now. As always let me know if I missed anything and if it's best to reopen it.
