### ISSUE TITLE
F-Droid listing

### ISSUE THREAD

**Issue by IzzySoft** [pastthepixels/FreePaint#6]
Hiho, as your app is available on F-Droid.org now for about 2 weeks, I'd usually remove it from IzzyOnDroid – but I see your Readme still links here. Does that mean I shall keep it here as well?

**Comment by pastthepixels** [comment]
I would say it's totally fine to remove it from IzzyOnDroid if you'd like! I just used the link because I noticed it was on IzzyOnDroid and though that'd be a much better place to download FreePaint than from the GitHub releases page before it got on F-Droid. Thanks for getting the app on IzzyOnDroid though, it's much appreciated!

**Comment by IzzySoft** [comment]
Yes, all fine! So to not cause any "404 confusion", I'll keep your app up here until you've removed the link from the Readme. Please give me a ping then, so I follow suit. Should at any point you need me to list your app again, just let me know – it's easily re-established.

**Comment by pastthepixels** [comment]
Thanks! I just removed the link from the README, so it should be good to remove now.

**Comment by IzzySoft** [comment]
Thanks! Will be gone here with the next sync then.
